# docker-compose.yaml
version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - awesome

  server-app:
    build:
      context: .
    ports:
      - "4000:3000"
    volumes:
      - ./shared:/var/www/shared
    depends_on:
       - mongo
    networks:
       - awesome

networks:
  awesome:
    driver: bridge
