ARG NODE_VERSION=16
ARG CLIENT_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY packages/client/package.json yarn.lock .
RUN yarn install --frozen-lockfile

COPY . .

RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

COPY --from=builder /app/packages/client/dist/ /app/

EXPOSE $CLIENT_PORT
CMD [ "npm", "run", "dev" ]
