ARG NODE_VERSION=16
ARG CLIENT_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/
COPY --from=builder /app/packages/client/ssr-dist/ /etc/ssr

EXPOSE $CLIENT_PORT
