version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
        depends_on:
          - postgres
        networks:
          - default
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        depends_on:
          - client
        networks:
          - default
    certbot:
      image: certbot/certbot
      depends_on:
        - server
      container_name: certbot
      volumes:
        - etc-letsencrypt:/etc/letsencrypt
        - www-html:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --mail test_mail@gmail.com --agree-tos --no-eff-email
      --staging -d best_game_ever.ru
    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
networks:
  outside:
    external: true

